echo updating and installing...
rm -rf LienePvP && apt upgrade && pkg install php && pkg install git && git clone https://github.com/PronixPvP/LienePvP.git && cd LienePvP && php buildPronix.php
echo Your install is finished
